### ISSUE TITLE
Markdown in issue description isn't parsed

### ISSUE THREAD

**Issue by limenet** [alorma/Gitskarios#42]
If there is any Markdown syntax in the issue description, it doesn't get parsed in the app i.e. it is displayed in plain text.

![2015-01-14 20 15 56](https://cloud.githubusercontent.com/assets/474329/5746804/abe12cb4-9c32-11e4-9065-a1c6f2c52a61.png)

(e.g. it should look like this: subject says "**in** two days", content says "two days **ago**")

**Comment by alorma** [comment]
Thanks for the feedback.

I will work on that for the next release, i want to highlight, and display images, etc...

Thanks.

**Comment by limenet** [comment]
You're welcome. I'm looking forward to it!
