### ISSUE TITLE
"Download source" button don't has an actual feedback

### ISSUE THREAD

**Issue by rocboronat** [alorma/Gitskarios#44]
The user may tap it without knowing what's happening. It's not an evidence that the button says "it will put a notification after some time and it will download the whole project", so the user don't realise what's happening when he taps it.

Easy way to solve it: 
1. A toast with "The download will start in few times"
2. Disabling the button when the user just tap it (it's common to download a .zip only once)
3. Adding visual feedback to the button (right now, the user isn't sure about if he tapped the button or not)

**Comment by alorma** [comment]
Thanks!

In fact i just see the user don't have feedback in any of three FAB buttons on Repo detail screen. I will fix that in the next release, and add some feedback for download, as well as branch selector to download.

**Comment by rocboronat** [comment]
Great!

**Comment by alorma** [comment]
FAB button feedback added on fd06c429bf0a750983c5aa260370062f1086ddf1
