### ISSUE TITLE
Can't login in GitSkarios

### ISSUE THREAD

**Issue by vinz243** [alorma/Gitskarios#47]
I'm creating this issue to sum up everything: I have  a phone under JB 4.2.2 and a tablet under same android. I tried to login on both and both failed. I can type my credentials, enter 2fa code and authorize app, but just after I get a blank screen.

 *  My phone is rooted with Xprivacy Greenify etc. But my tablett isn't and it doesn't work either.
 *  I tried debugging (using console.log :P). [This](https://github.com/alorma/Gitskarios/blob/master/app/src/main/java/com/alorma/github/ui/activity/LoginActivity.java#L102) line was called every time webview location changed, except for gitskarios.com domain.
 * Once I tapped on authroize other links such as Github, Alorma... are unresponsive

Perhaps I could add the oauth key to the settings as hack

**Comment by vinz243** [comment]
So here is what I tried step by step.

1. Installed GitSkarios
2. Logged in in GitSkarios and then got blank screen.
3. Logged in in chrome
4. Shutdown WiFi/3G
5. Reopened GitSkarios. Got page not accessible for github.com/authorize.... Copied this URL
6. Turned on WiFi and paste URL. Redirected to gitskarios.com/oauth?key=<key>
7. Opened Preference Manager and for GitSkarios added a key `StoreCredentials.USER_TOKEN`, with value the <key>. 
8. Opened gitskarios. Saw UI (at least!), but saw toast Unauthorized or something like that, and got blank page :'(

**Comment by alorma** [comment]
I finally got a phone that reproduces this bug!

Testing, should it be fixed soon.

**Comment by vinz243** [comment]
Good news !!!
What phone is it?

**Comment by alorma** [comment]
It's a galaxy S3, stock ROM not rooted

**Comment by vinz243** [comment]
Oh. I have a S3 Mini VE, with a stock deodexed ROM and rooted

**Comment by vinz243** [comment]
Any progress on this issue? i cn't wait using gitksarios :smile:

**Comment by vinz243** [comment]
Seems this guys has the same problem as me https://play.google.com/store/apps/details?id=com.alorma.github&reviewId=Z3A6QU9xcFRPRkZrTnhyU3lzTDRZUHNuZTVNN25CNGZTLVRrSE1WUUpZM1loZ04ydTRuZkdOc21SRXZ5YUFUakt3bi1jNFEwZGpRMlIzZjJVZkZvV0FwZkQ0&hl=fr

**Comment by alorma** [comment]
No news yet :(

I will try to implement an alternative login, to skip the website login... news soon.

**Comment by alorma** [comment]
Sadly i will discontinue the project in front of the new github official app (it have Material Design now)

**Comment by vinz243** [comment]
A pity. But the official github app doesn't have material design yet, does it?

Envoyé par Blue Mail



Sur 15 Fév 2015 à 19:37, à 19:37, "Bernat Borrás Paronella" <notifications@github.com> a écrit:

**Comment by alorma** [comment]
Not yet, but they are updating, take a look at the repo and compile
yourself... :(

I will make new projects!

**Comment by vinz243** [comment]
Thank you now it works like a charm !!! BTW I'm glad you're still developing it :)
