### ISSUE TITLE
Can't add issues

### ISSUE THREAD

**Issue by JgrindleGit** [alorma/Gitskarios#50]
When attempting to create a new issue, my screen goes static. Running android 5.0 on nexus 5.

**Comment by alorma** [comment]
What you mean with 'goes static'?

App crashes, not react? It completes the issue or fails on that?

**Comment by JgrindleGit** [comment]
It was crashing when this was happening. The app was failing and wouldn't create the issue. By goes static, like a static on an older television.

**Comment by JgrindleGit** [comment]
It was crashing when this was happening. The app was failing and wouldn't create the issue. By goes static, like a static on an older television
