### ISSUE TITLE
Issue with the plus button in the "add issue" screen

### ISSUE THREAD

**Issue by rocboronat** [alorma/Gitskarios#70]
When the user taps the button, it doesn't have any feedback. So, the user taps again again and again and he creates 3 issues instead of one.

**Comment by Hauwertlhaufn** [comment]
Maybe it is possible to redirect the user directly to the new opened issue.

**Comment by alorma** [comment]
Add feedback
https://github.com/alorma/Gitskarios/commit/7b06c32fb39996028b89db790c0d352b5f58a3c4

**Comment by alorma** [comment]
As @Hauwertlhaufn said:
https://github.com/alorma/Gitskarios/commit/604c1999f064e647b0abd00f745b8001cddfb0d6

I implemented that if create a issue, automatic open the issue.
