### ISSUE TITLE
issue details scrollable

### ISSUE THREAD

**Issue by Hauwertlhaufn** [alorma/Gitskarios#80]
Some issue details are not shown completly if they are too long. They are also not scrollable. (Nexus 5, Android 5.1)
Example: https://github.com/cgeo/cgeo/issues/4861
![issue-details](https://cloud.githubusercontent.com/assets/9079777/7064789/c9662192-deb1-11e4-9d82-2e1b74f057f7.png)

**Comment by alorma** [comment]
I'm working in a full redesign of the issue content. thanks :D

**Comment by alorma** [comment]
Resolved on v.2.2.0
