### ISSUE TITLE
No repositories found when browsing remote organizations

### ISSUE THREAD

**Issue by siracuervo** [alorma/Gitskarios#81]
for example i go to organization tab in the drawer, search omni, i enter to omnirom, and click repos, then a message "No repositories found" appears, with every org which is not one of mines

**Comment by alorma** [comment]
Ok.

I found the problem, i wil fix it soon.

Thanks

**Comment by alorma** [comment]
Fixed in version 2.2.0.

Thanks for your feedback.

**Comment by siracuervo** [comment]
Thanks man! Now making it my git browser
