### ISSUE TITLE
repository menue enhances every time it is shown and hidden again

### ISSUE THREAD

**Issue by Hauwertlhaufn** [alorma/Gitskarios#82]
On my forks the menue enhances every time I hit it. Example: cgeo.github.io (  https://github.com/Hauwertlhaufn/cgeo.github.io )
If I close the fork and open it again, it starts with one menue again. (Nexus 5, Android 5.1)
Normal:
![screenshot_1](https://cloud.githubusercontent.com/assets/9079777/7101469/6f76bd08-e05b-11e4-856f-a8f540372d7c.png)

second time:
![screenshot_2015-04-11-13-15-50](https://cloud.githubusercontent.com/assets/9079777/7101470/8b73c492-e05b-11e4-8e88-b7cd92593826.png)

sixth time:
![screenshot_2015-04-11-13-16-07](https://cloud.githubusercontent.com/assets/9079777/7101472/9cc43722-e05b-11e4-8f9b-aaeef0e6bccc.png)

**Comment by alorma** [comment]
Ups!

Thanks for that, i will fix in the next release

**Comment by Hauwertlhaufn** [comment]
No problem.

**Comment by alorma** [comment]
Fixed in version 2.3.0
