### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by mkoch227** [alorma/Gitskarios#88]
_(This is more of a question than an actual "issue")_

I'm currently trying to compile and run a dev version of Gitskarios, and I'm currently unsure exactly what my callback URL should be.  Is there a URL prefix (such as `gitskarios://...`)? I'm a complete novice when it comes to Android development, so I apologize in advance for my confusion :grinning:.  I'm able to compile the app with no problems, and was able to register the application on GitHub; however the callback URL is currently set to my website, which obviously is incorrect.

**Comment by alorma** [comment]
Hi.

Yes, the current branch needs a prefix, but you can configure it in your gradle.properties too.

Setup your custom prefix in OAuth Applicaion page, like "myapp://", and then configure gitskarios with gradle .properties.
